# Generated by Django 5.0.7 on 2024-07-22 16:58

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='koodak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=250)),
                ('cod_meli', models.IntegerField()),
                ('mahal_tavalod', models.CharField(max_length=250)),
                ('datetime', django_jalali.db.models.jDateField()),
                ('namepedar', models.CharField(max_length=250)),
                ('tahsilatpedar', models.CharField(max_length=250)),
                ('shoghlepedar', models.CharField(max_length=250)),
                ('telpedar', models.IntegerField()),
                ('adress_p', models.CharField(max_length=250)),
                ('namemadar', models.CharField(max_length=250)),
                ('tahsilatmadar', models.CharField(max_length=250)),
                ('shoghlmadar', models.CharField(max_length=250)),
                ('telmadar', models.IntegerField()),
                ('telsabet', models.CharField(max_length=250)),
                ('adress_m', models.CharField(max_length=250)),
                ('adressmanzel', models.CharField(max_length=250)),
                ('codeposti', models.IntegerField()),
                ('vatsap', models.IntegerField()),
                ('imagk', models.ImageField(upload_to='files/koodak')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=250)),
                ('cod_meli', models.IntegerField()),
                ('mahal_tavalod', models.CharField(max_length=250)),
                ('datetime', django_jalali.db.models.jDateField()),
                ('mizantahsilat', models.CharField(max_length=250)),
                ('reshtetahsili', models.CharField(max_length=250)),
                ('doreamozeshi', models.CharField(max_length=400)),
                ('sabeghekar', models.CharField(max_length=200)),
                ('savabeghshoghli', models.CharField(max_length=400)),
                ('semat', models.CharField(max_length=250)),
                ('elattarkkar', models.CharField(max_length=400)),
                ('semataknon', models.CharField(max_length=250)),
                ('tahol', models.CharField(max_length=250)),
                ('namehamsar', models.CharField(max_length=250)),
                ('tedadfarzand', models.CharField(max_length=200)),
                ('tel', models.IntegerField()),
                ('telsabet', models.IntegerField()),
                ('adress_m', models.CharField(max_length=250)),
                ('imagp', models.ImageField(upload_to='files/personel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
