# Generated by Django 5.0.7 on 2024-07-24 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namefull', models.CharField(max_length=250, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=250)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('masg', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'نظر ',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('film', models.FileField(upload_to='files/film')),
            ],
        ),
        migrations.CreateModel(
            name='movik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imagek', models.ImageField(upload_to='files/koodak')),
            ],
        ),
        migrations.CreateModel(
            name='movip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imagep', models.ImageField(upload_to='files/personel')),
            ],
        ),
        migrations.CreateModel(
            name='ask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('caption', models.CharField(max_length=2000)),
                ('created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سوال ',
                'verbose_name_plural': 'سوال ها',
            },
        ),
        migrations.CreateModel(
            name='commentask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=2000)),
                ('created', models.DateTimeField()),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelapp.ask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جواب سوال ها ',
                'verbose_name_plural': 'جواب ها',
            },
        ),
    ]
