# Generated by Django 5.0.7 on 2024-08-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0002_contactus_films_movik_movip_ask_commentask'),
    ]

    operations = [
        migrations.CreateModel(
            name='clas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameclas', models.CharField(max_length=250, verbose_name='نام کلاس')),
                ('namemorabi', models.CharField(max_length=250)),
                ('roz', models.CharField(max_length=50)),
                ('time', models.TimeField(max_length=50, verbose_name='')),
            ],
            options={
                'verbose_name': ' کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='imgmahd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imagek', models.ImageField(upload_to='files/mahd')),
            ],
        ),
        migrations.CreateModel(
            name='veblog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='نام کامل')),
                ('post', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'وبلاگ ',
                'verbose_name_plural': 'جزیات وبلاگ',
            },
        ),
    ]
