# Generated by Django 5.0.7 on 2024-08-01 11:53

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0003_clas_imgmahd_veblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameclas', models.CharField(max_length=250, verbose_name='نام کلاس')),
                ('namemorabi', models.CharField(max_length=250)),
                ('roz', models.CharField(max_length=50)),
                ('time', models.TimeField(max_length=50, verbose_name='')),
                ('age', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tedad_jalasat', models.CharField(max_length=50, null=True)),
                ('datetime', django_jalali.db.models.jDateField()),
            ],
            options={
                'verbose_name': ' کلاس',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
        migrations.RenameField(
            model_name='imgmahd',
            old_name='imagek',
            new_name='imgmahd',
        ),
    ]
