# Generated by Django 5.0.7 on 2024-08-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0004_clasmodel_rename_imagek_imgmahd_imgmahd'),
    ]

    operations = [
        migrations.CreateModel(
            name='veblogp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('clasmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelapp.clasmodel')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panelapp.personel')),
            ],
        ),
    ]
