# Generated by Django 4.2.14 on 2024-08-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0005_veblogp'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgnaghashi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgmahd', models.ImageField(upload_to='files/naghashi')),
            ],
        ),
        migrations.CreateModel(
            name='imgpish1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgmahd', models.ImageField(upload_to='files/pish1')),
            ],
        ),
        migrations.CreateModel(
            name='imgpish2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgmahd', models.ImageField(upload_to='files/pish2')),
            ],
        ),
        migrations.CreateModel(
            name='imgvarzesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgmahd', models.ImageField(upload_to='files/varzesh')),
            ],
        ),
    ]
