# Generated by Django 4.2.14 on 2024-08-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0006_imgnaghashi_imgpish1_imgpish2_imgvarzesh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasmodel',
            name='time',
            field=models.TimeField(max_length=50),
        ),
    ]
