# Generated by Django 4.2.14 on 2024-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0007_alter_clasmodel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_collation='', max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, db_collation='', max_length=200, unique=True)),
            ],
        ),
    ]
