# Generated by Django 4.2.14 on 2024-08-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
