# Generated by Django 4.2.14 on 2024-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelapp', '0013_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='files/image')),
                ('filter_choice', models.CharField(max_length=200)),
            ],
        ),
    ]
